# Site settings
title: Eyal Gur, Ph.D. â€“ Projects and Publications
description: I am an algorithm developer and researcher specializing in optimization problems within deep and machine learning, signal processing, data science, statistics, operations research, mathematics, and other related domains.
description: dsfsdfsd.
theme: jekyll-theme-cayman # Theme name or other theme settings

# Build settings
markdown: kramdown
